### ISSUE TITLE
Sword Perks TODO

### ISSUE THREAD

**Issue by Exo2986** [ExoMaster/ProjectAres#1]
- [x] Rampage: Kills temporarily increase damage dealt, stacks up to 3x.
- [x] Thrill of the Kill: Kills temporarily increase swing speed, stacks up to 3x.
- [x] Evasion: Double tap movement keys to dodge.
- [x] Top Heavy: Increases damage to enemies hit from a distance.
- [x] Eternal: Stays in the player's inventory upon death
- [x] Extended Blade: Increases attack range
- [x] Adrenaline Rush: Taking damage temporarily increases swing speed
- [x] Holy Fire: Hits have a chance to set the target on fire. The fire will spread to nearby enemies over time
- [x] Confusion: Causes nearby enemies to attack each other.
- [x] Magnetic: Enemies wearing or holding metal objects will be passively pulled toward the player.
- [x] Copper Coating: Enemies will be struck by lightning when hit while raining.
- [x] Surrounded: Greatly increases damage proportional to amount of nearby enemies.
- [x] Soul Capacitor: Each kill charges this weapon. Right clicking will consume a charge and deal massive AOE damage around the player.
- [x] Freezing: Applies slowness to enemies when hit. Multiple stacks of this effect will cause damage over time.
- [x] Final Stand: When the player would die, stay at 1/2 heart with temporary regeneration. Long cooldown.
- [x] Killing Wind: Kills grant swiftness
- [x] Vampirism: Attacks heal the player.
- [x] Vortex Strike: Crits deal AOE damage around the target.
- [ ] Upslash: Right clicking on an enemy will send them flying upwards.
- [x] Moving Target: Greatly increases swing speed while moving.
- [x] Hold Your Ground: Greatly increases damage whilst stationary.
- [ ] Elemental Affinity: Deals freezing damage while standing on snow, fire damage while in the nether, etc.
- [ ] Obsidian Plating: Greatly reduces swing speed, but increases damage. Successful hits emit a shockwave and damage enemies in a line behind the target.
- [x] Critical Spec: Fully charged attacks will always result in a critical hit.
- [x] Eye for an Eye: Damage taken will be applied to target on next attack.
- [ ] Dark Knight: Increased damage dealt while in the dark.
- [ ] Ignition Coil: Attacks ignite creepers.
- [x] Chorus Imbued: Instead of dying, teleport to a random location nearby with 1/2 heart. Long cooldown.
